name: AZClientAPI
version: '${project.version}'
description: A plugin to integrate the AZ Launcher.
main: fr.speccy.azclientapi.bukkit.AZClientPlugin
depend: [ProtocolLib]
author: [Speccy, MATHIP6]
commands:
  az:
    description: A AZ command
    permission: azclientapi.command
